[metadata]
name = sasci360solworkflow
version = 0.0.1
author = Nelson Grey LLC
author_email = support@nelsongrey.com
description = Python client for SAS Customer Intelligence 360 Workflow APIs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mnelson3/sas-ci360-sol-workflow
project_urls = Bug Tracker = https://github.com/mnelson3/sas-ci360-sol-workflow/issues
classifiers = Programming Language :: Python :: 3
	License :: Other/Proprietary License
	Operating System :: OS Independent

[options]
package_dir = = src
packages = find:
python_requires = >=3.8
install_requires =
	PyJWT>=2.0.0
	requests>=2.31.0
	urllib3>=1.26.9

[options.packages.find]
where = src
